import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Appbar from '@/component/appbar/Appbar'
import Footer from "@/component/footer/Footer";
import AuthProvider from "@/component/Authprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
        <Appbar/>
        {children}
        <Footer/>
        </AuthProvider>
        </body>
    </html>
  );
}
